# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: nightly build

on:
  #schedule:
  #  - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8 pytest coverage gpu4pyscf-libxc-cuda11x pytest-cov pyscf-dispersion
        pip3 install pyscf --upgrade
        git config --global core.compression 9
    - name: Build GPU4PySCF
      run: |
        export CUDA_HOME=/usr/local/cuda
        export PATH=${CUDA_HOME}/bin:${PATH}
        export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH
        sh build.sh
    - name: Smoke Test
      run: |
        echo $GITHUB_WORKSPACE
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest --durations=0
